/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rafiq
 */
public class library_management extends javax.swing.JFrame {

    /**
     * Creates new form library_management
     */
    static Connection con = null;
    static PreparedStatement ps = null;
    static ResultSet rs = null;
    
    public library_management() {
        initComponents();
        con = configuration.db_connect();
        setResizable(false);
        setSize(730, 500);
         
        setTitle("LIBRARY MANAGEMENT");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);
        settings();
    }
    
    public void settings()
    {
        settingsPanel.setBorder(new TitledBorder(null, "CHANGE PASSWORD", TitledBorder.LEADING, 
				TitledBorder.TOP, null, null));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_allBooks = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAllBooks = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        books_name_search = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        books_no = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        books_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        copies = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        availableBooks = new javax.swing.JTextField();
        addBooks = new javax.swing.JButton();
        updateBooks = new javax.swing.JButton();
        deleteBooks = new javax.swing.JButton();
        cleareBooks = new javax.swing.JButton();
        exitBooks = new javax.swing.JButton();
        jComboBoxBooks = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        reg_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        issue_books_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooserIssue = new com.toedter.calendar.JDateChooser();
        issueBooks = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        availableCopyIssue = new javax.swing.JTextField();
        jComboBox_issue_dept = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        return_reg_no = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        return_books_no = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_return_dept = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jDateChooserReturn = new com.toedter.calendar.JDateChooser();
        returnBooks = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        inqueryRegNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox_inqueryDept = new javax.swing.JComboBox();
        inquery = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inqueryTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        currentPass = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        newPass = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        confirmPass = new javax.swing.JTextField();
        changePass = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        newEmail = new javax.swing.JTextField();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setText("Department :");

        jComboBox_allBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox_allBooks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "CE" }));
        jComboBox_allBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_allBooksActionPerformed(evt);
            }
        });

        tableAllBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "books_no", "books_name", "author", "edition", "copies"
            }
        ));
        jScrollPane1.setViewportView(tableAllBooks);

        jLabel25.setText("Books Name:");

        books_name_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books_name_searchActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("SERCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_allBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(books_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_allBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(books_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("All Books", jPanel1);

        jLabel2.setText("Books No :");

        books_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                books_noKeyReleased(evt);
            }
        });

        jLabel3.setText("Name :");

        jLabel4.setText("Author:");

        jLabel5.setText("Edition:");

        jLabel6.setText("Dept:");

        jLabel7.setText("Copies");

        jLabel8.setText("Available Copy");

        addBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBooks.setText("ADD");
        addBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksActionPerformed(evt);
            }
        });

        updateBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBooks.setText("UPDATE");
        updateBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBooksActionPerformed(evt);
            }
        });

        deleteBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBooks.setText("DELETE");
        deleteBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBooksActionPerformed(evt);
            }
        });

        cleareBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cleareBooks.setText("CLEARE");
        cleareBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleareBooksActionPerformed(evt);
            }
        });

        exitBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBooks.setText("EXIT");
        exitBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBooksActionPerformed(evt);
            }
        });

        jComboBoxBooks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "CE" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleareBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBooks)
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(books_no)
                                    .addComponent(books_name)
                                    .addComponent(author)
                                    .addComponent(edition)
                                    .addComponent(copies, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(availableBooks))
                                .addGap(149, 149, 149))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(books_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(books_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(copies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBooks)
                    .addComponent(updateBooks)
                    .addComponent(deleteBooks)
                    .addComponent(cleareBooks)
                    .addComponent(exitBooks))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Books", jPanel2);

        jLabel9.setText("Reg:");

        jLabel10.setText("Books No:");

        issue_books_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                issue_books_noKeyReleased(evt);
            }
        });

        jLabel11.setText("Dept:");

        jLabel12.setText("Date:");

        issueBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issueBooks.setText("ISSUE");
        issueBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBooksActionPerformed(evt);
            }
        });

        jLabel13.setText("Available Copy");

        jComboBox_issue_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "CE" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(issue_books_no)
                                        .addComponent(jDateChooserIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(availableCopyIssue)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox_issue_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(issueBooks)))
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(issue_books_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(availableCopyIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_issue_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jDateChooserIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(issueBooks)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issue Books", jPanel3);

        jLabel14.setText("Reg:");

        return_reg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_reg_noActionPerformed(evt);
            }
        });

        jLabel15.setText("Books No:");

        jLabel16.setText("Dept:");

        jComboBox_return_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "CE" }));

        jLabel17.setText("Date:");

        returnBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnBooks.setText("RETURN");
        returnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnBooks)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_return_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(return_reg_no)
                        .addComponent(return_books_no)
                        .addComponent(jDateChooserReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(return_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(return_books_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox_return_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jDateChooserReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(returnBooks)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Return Books", jPanel4);

        jLabel18.setText("Reg:");

        jLabel19.setText("Dept:");

        jComboBox_inqueryDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "CE" }));

        inquery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inquery.setText("SHOW");
        inquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inqueryActionPerformed(evt);
            }
        });

        inqueryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "books_no", "books_name", "author", "edition", "issue_date", "return_date"
            }
        ));
        jScrollPane2.setViewportView(inqueryTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inqueryRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_inqueryDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inquery)
                        .addGap(130, 130, 130))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(inqueryRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox_inqueryDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inquery))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inquery", jPanel5);

        jLabel20.setText("Current E-mail:");

        jLabel21.setText("Current Password:");

        jLabel22.setText("New Password:");

        jLabel23.setText("Confirm Password:");

        changePass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changePass.setText("SUBMIT");
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });

        jLabel24.setText("New E-mail:");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePass)
                .addGap(152, 152, 152))
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(newEmail))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(currentPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(changePass)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(170, 170, 170))
        );

        jTabbedPane1.addTab("Settings", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_reg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_reg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_reg_noActionPerformed

    private void jComboBox_allBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_allBooksActionPerformed
        // TODO add your handling code here:
        try{
            String query = "select books_no,books_name,author,edition,copies from books where dept = ? ";
            ps = con.prepareStatement(query);
            ps.setString(1, jComboBox_allBooks.getSelectedItem().toString());
            rs = ps.executeQuery();

            tableAllBooks.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_allBooksActionPerformed

    private void books_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_books_noKeyReleased
        // TODO add your handling code here:
        try{
            String query = "select * from books where books_no = ?";
            ps = con.prepareStatement(query);
            ps.setString(1, books_no.getText());
            rs = ps.executeQuery();

            while(rs.next())
            {
                //dept.setText(rs.getString("dept"));
                books_name.setText(rs.getString("books_name"));
                author.setText(rs.getString("author"));
                edition.setText(rs.getString("edition"));
                availableBooks.setText(rs.getString("copies"));
            }
            ps.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_books_noKeyReleased

    private void addBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBooksActionPerformed
        // TODO add your handling code here:
        String Dept = jComboBoxBooks.getSelectedItem().toString();
        String booksNo = books_no.getText();
        String booksName = books_name.getText();
        String Author = author.getText();
        String Edition = edition.getText();
        String Copies = copies.getText();
        int C = Integer.parseInt(Copies);

        String sql = "insert into books values('"+booksNo+"','"+booksName+"','"+Author+"','"+Edition+"','"+C+"','"+Dept+"');";
        try{
            con.prepareStatement(sql).execute();
            JOptionPane.showMessageDialog(null, "Successfully Inserted Books");
        }catch(Exception e)
        {
            System.out.println(" Error in Add !!");
        }
    }//GEN-LAST:event_addBooksActionPerformed

    private void updateBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBooksActionPerformed
        // TODO add your handling code here:
        try {
            String Dept = jComboBoxBooks.getSelectedItem().toString();
            String booksNo = books_no.getText();
            String booksName = books_name.getText();
            String Author = author.getText();
            String Edition = edition.getText();
            String Copies = copies.getText();
            int Cop = Integer.parseInt(Copies);

            String sql = "update books set books_no = '"+booksNo+"', Books_name = '"+booksName+"',author = '"+Author+"',edition = '"+Edition+"' ,copies = '"+Cop+"',dept = '"+Dept+"' where books_no = '"+booksNo+"'";

            con.prepareStatement(sql).execute();
            JOptionPane.showMessageDialog(null, "Successfully Updated Books");
        }catch(Exception e)
        {
            System.out.println(" Error in Update !!");
        }
    }//GEN-LAST:event_updateBooksActionPerformed

    private void deleteBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBooksActionPerformed
        // TODO add your handling code here:
        String booksNo = books_no.getText();
        String Dept = jComboBoxBooks.getSelectedItem().toString();

        String sql = "DELETE FROM books WHERE books_no = '"+booksNo+"' and dept = '"+Dept+"'";
        try{
            ps = con.prepareStatement(sql);
            //ps.setString(1, booksNo);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Successfully Deleted Books");
        }catch(Exception e)
        {
            System.out.println(" Error in Delete !!");
        }
    }//GEN-LAST:event_deleteBooksActionPerformed

    private void cleareBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleareBooksActionPerformed
        // TODO add your handling code here:
        books_no.setText("");
        books_name.setText("");
        author.setText("");
        edition.setText("");
        copies.setText("");
        availableBooks.setText("");
    }//GEN-LAST:event_cleareBooksActionPerformed

    private void exitBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBooksActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBooksActionPerformed

    private void issueBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBooksActionPerformed
        // TODO add your handling code here:
        int chk = 0;
        String reg = reg_no.getText();
        String booksNo = issue_books_no.getText();
        String isu_dept = jComboBox_issue_dept.getSelectedItem().toString();
        String issueDate = ((JTextField)jDateChooserIssue.getDateEditor().getUiComponent()).getText();
        
        String c = availableCopyIssue.getText();
        int cc = Integer.parseInt(c);
        //System.out.println(cc);
        if(cc>0){
            cc = cc - 1;
        String sql1 = "update books set copies = '"+cc+"' where books_no = '"+booksNo+"' and dept = '"+isu_dept+"'";
        try{
            con.prepareStatement(sql1).execute();
            
        }catch(Exception e)
        {
            System.out.println(" Error in update !!");
            
        }
        
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Not available books !!");
            chk = 1;
        }
        
        if(chk==0){
        String sql = "insert into issuereturn values('"+reg+"','"+booksNo+"','"+isu_dept+"','"+issueDate+"','"+"X"+"')";
        try{
            con.prepareStatement(sql).execute();
            JOptionPane.showMessageDialog(null, "Successfully Issue Books");
        }catch(Exception e)
        {
            System.out.println(" Error in insert issuereturn !!");
        }
        }
    }//GEN-LAST:event_issueBooksActionPerformed

    private void inqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inqueryActionPerformed
        // TODO add your handling code here:
        String sql = "select books_no,books_name,author,edition,issue_date,return_date FROM books natural join issuereturn  where reg_no = '"+inqueryRegNo.getText()+"' and dept = '"+jComboBox_inqueryDept.getSelectedItem().toString()+"'";
        try{
            ps = con.prepareStatement(sql);
            //ps.setString(1, searchBooksNo.getText());
            ResultSet rs = ps.executeQuery();
            inqueryTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            System.out.println(" Error in Inquery !!");
        }
    }//GEN-LAST:event_inqueryActionPerformed

    private void returnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBooksActionPerformed
        // TODO add your handling code here:
        String reg = return_reg_no.getText();
        String booksNo = return_books_no.getText();
        String isu_dept = jComboBox_return_dept.getSelectedItem().toString();
        String returnDate = ((JTextField)jDateChooserReturn.getDateEditor().getUiComponent()).getText();

        String sql = "insert into issuereturn values('"+reg+"','"+booksNo+"','"+isu_dept+"','"+"X"+"','"+returnDate+"');";
        try{
            con.prepareStatement(sql).execute();
            JOptionPane.showMessageDialog(null, "Successfully Returned Books");
        }catch(Exception e)
        {
            System.out.println(" Error in Returned !!");
        }
        
        String sql2 = "update books set copies = copies+1 where books_no='"+booksNo+"' and dept='"+isu_dept+"'";
        try{
            con.prepareStatement(sql2).execute();
            
        }catch(Exception e)
        {
            System.out.println(" Error in update !!");
        }
    }//GEN-LAST:event_returnBooksActionPerformed

    private void issue_books_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issue_books_noKeyReleased
        // TODO add your handling code here:
        try{
            String query = "select * from books where books_no = ? ";
            ps = con.prepareStatement(query);
            ps.setString(1, issue_books_no.getText());
            rs = ps.executeQuery();

            while(rs.next())
            {
                availableCopyIssue.setText(rs.getString("copies"));
                
            }
            ps.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_issue_books_noKeyReleased

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        // TODO add your handling code here:
        String em = email.getText();
        String nEm = newEmail.getText();
        String crntPass = currentPass.getText();
        String nPass = newPass.getText();
        String confPass = confirmPass.getText();

        String sql = "select * from log_in";

        String a = "";
        String b = "";
        String c = "1";

        try{
            rs=con.prepareStatement(sql).executeQuery();

            if(!nPass.equals(confPass))
            {
                JOptionPane.showMessageDialog(null, "Password does not match","Failed",JOptionPane.ERROR_MESSAGE);
            }
            else{

                if(rs.next())
                {
                    a = rs.getString("password");
                    b = rs.getString("email");
                    if(crntPass.equals(a) && em.equals(b))
                    {
                        String sql1 = "update log_in set email = '"+nEm+"' ,password = '"+nPass+"' where sl = '"+c+"'";
                        try{

                            con.prepareStatement(sql1).execute();
                            System.out.println("accessed");
                            JOptionPane.showMessageDialog(null, "Password Changed","Successfull",JOptionPane.ERROR_MESSAGE);
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null,e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Wrong Current Password or Email","Failed",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "error","error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_changePassActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        /*Border border = BorderFactory.createEmptyBorder();
        logOut.setBorder(border);
        logOut.setContentAreaFilled(false);
        logOut.setFocusPainted(false);*/
        LogInPage ob = new LogInPage();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void books_name_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books_name_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_books_name_searchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String name = books_name_search.getText();

        String sql = "select * from books where books_name='"+name+"'";
        try{
            ps = con.prepareStatement(sql);
            //ps.setString(1, searchBooksNo.getText());
            ResultSet rs = ps.executeQuery();
            tableAllBooks.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e)
        {
            System.out.println(" Error in search!!");
        }
        
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(library_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(library_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(library_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(library_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new library_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBooks;
    private javax.swing.JTextField author;
    private javax.swing.JTextField availableBooks;
    private javax.swing.JTextField availableCopyIssue;
    private javax.swing.JTextField books_name;
    private javax.swing.JTextField books_name_search;
    private javax.swing.JTextField books_no;
    private javax.swing.JButton changePass;
    private javax.swing.JButton cleareBooks;
    private javax.swing.JTextField confirmPass;
    private javax.swing.JTextField copies;
    private javax.swing.JTextField currentPass;
    private javax.swing.JButton deleteBooks;
    private javax.swing.JTextField edition;
    private javax.swing.JTextField email;
    private javax.swing.JButton exitBooks;
    private javax.swing.JButton inquery;
    private javax.swing.JTextField inqueryRegNo;
    private javax.swing.JTable inqueryTable;
    private javax.swing.JButton issueBooks;
    private javax.swing.JTextField issue_books_no;
    private javax.swing.JComboBox jComboBoxBooks;
    private javax.swing.JComboBox jComboBox_allBooks;
    private javax.swing.JComboBox jComboBox_inqueryDept;
    private javax.swing.JComboBox jComboBox_issue_dept;
    private javax.swing.JComboBox jComboBox_return_dept;
    private com.toedter.calendar.JDateChooser jDateChooserIssue;
    private com.toedter.calendar.JDateChooser jDateChooserReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField reg_no;
    private javax.swing.JButton returnBooks;
    private javax.swing.JTextField return_books_no;
    private javax.swing.JTextField return_reg_no;
    private javax.swing.JButton search;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JTable tableAllBooks;
    private javax.swing.JButton updateBooks;
    // End of variables declaration//GEN-END:variables
}
